version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "080425"
      POSTGRES_DB: personal_finance
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d personal_finance"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:5000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    # Perintah untuk menjalankan migrasi dan server secara berurutan
    command: sh -c "npm run migrate && npm start"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3002:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.production
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:
