version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "080425"
      POSTGRES_DB: personal_finance
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:5000"
    environment:
      PGUSER: postgres
      PGHOST: db
      PGDATABASE: personal_finance
      PGPASSWORD: "080425"
      PGPORT: 5432
      JWT_SECRET: supersecretjwtkey
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3002:3000"
    environment:
      VITE_API_URL: http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf # Menambahkan volume untuk konfigurasi Nginx

volumes:
  postgres_data:
