version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "080425"
      POSTGRES_DB: personal_finance
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:5000"
    depends_on:
      - db
    # Mengarahkan Docker untuk memuat file .env dari dalam folder backend
    env_file:
      - ./backend/.env
    # Menghapus duplikasi variabel yang sudah ada di .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3002:3000"
    depends_on:
      - backend
    env_file:
      - ./.env.production
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
      
volumes:
  postgres_data:
